pod_namespace: jx
prowjob_namespace: jx
postsubmits:
  gitcpu-io/jx-azure:
  - agent: tekton-pipeline
    branches:
      - main
    context: jx-azure
    name: jx-azure
    pipeline_run_spec:
      serviceAccountName: app-builder
      pipelineRef:
        name: jx-azure-pipeline
      workspaces:
        - name: shared-workspace
          persistentvolumeclaim:
            claimName: buildpacks-source-pvc
      resources:
        - name: build-image
          resourceRef:
            name: buildpacks-app-image
      podTemplate:
        volumes:
          - name: buildpacks-cache
            persistentVolumeClaim:
              claimName: buildpacks-cache-pvc
presubmits:
  gitcpu-io/jx-azure:
    always_run: true
    context: serverless-jenkins
    name: serverless-jenkins
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
tide:
  queries:
  - repos:
    - gitcpu-io/jx-azure
    labels:
    - approved
