pod_namespace: jx
prowjob_namespace: jx
postsubmits:
  gitcpu-io/jx-azure: #org/repo的名字,这里需要替换
  - agent: tekton-pipeline
    branches:
      - main  #确定你的仓库也是main的分支，如果是master请修改
    context: jx-azure
    name: jx-azure
    pipeline_run_spec:  #这里的pipeline运行spec需要是上面创建的名字
      serviceAccountName: app-builder
      pipelineRef:
        name: jx-azure-pipeline
      workspaces:
        - name: shared-workspace
          persistentvolumeclaim:
            claimName: buildpacks-source-pvc
      resources:
        - name: build-image
          resourceRef:
            name: buildpacks-app-image
      podTemplate:
        volumes:
          - name: buildpacks-cache
            persistentVolumeClaim:
              claimName: buildpacks-cache-pvc
presubmits:
  gitcpu-io/jx-azure: #org/repo的名字,这里需要替换
  - agent: tekton
    always_run: true
    context: serverless-jenkins
    name: serverless-jenkins
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
tide:
  queries:
  - repos:
    - gitcpu-io/jx-azure  #org/repo的名字,这里需要替换
    labels:
    - approved

