name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: my-app-install token
        id: my-app
        uses: gitcpu-io/jx-azure@main
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: gitcpu-io/action-github-app-token
          token: ${{ steps.my-app.outputs.token }}   
